# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spreedly}
  s.version = "1.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Delano Mandelbaum"]
  s.date = %q{2011-01-25}
  s.description = %q{A library for Spreedly (the payment service) based on Terralien's lib by Nathaniel Talbott}
  s.email = %q{delano@solutious.com}
  s.extra_rdoc_files = [
    "README.txt",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     ".gitmodules",
     ".rvmrc",
     "History.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "TODO",
     "VERSION.yml",
     "lib/spreedly.rb",
     "lib/spreedly/common.rb",
     "lib/spreedly/mock.rb",
     "lib/spreedly/test_hacks.rb",
     "lib/spreedly/version.rb",
     "test/spreedly_gem_test.rb",
     "test/test_site.example.yml"
  ]
  s.homepage = %q{http://github.com/delano/spreedly-gem}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{spreedly}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A library for Spreedly (the payment service) based on Terralien's lib by Nathaniel Talbott}
  s.test_files = [
    "test/spreedly_gem_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end

